//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string VendorEmail { get; set; }
        public int VendorAge { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public int GenreId { get; set; }
        public int AuthorId { get; set; }
        public int PublisherId { get; set; }
        public decimal Price { get; set; }
        [NotMapped]
        public string GenreName { get; set; }
        [NotMapped]
        public string AuthorName { get; set; }
        [NotMapped]
        public string PublisherName { get; set; }
    }
}
